spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group

