spring:
  kafka:
    bootstrap-servers:
      - kafka:29092
    template:
      default-topic: library-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
